### ISSUE TITLE
Add  feature to delete tables

### ISSUE THREAD

**Issue by chrwm** [sedos-project/sedos_upload#3]
- [x] Enables the possibility to delete a list of tables

**Comment by chrwm** [comment]
Currently this code doesn't work

https://github.com/sedos-project/sedos_upload/blob/97c686ea8d44ef0ef36680a21e320c2e22b2eac3/main.py#L229-L235

It is taken from [here](https://openenergyplatform.github.io/academy/tutorials/01_api/02_api_upload/#delete-table). Is this outdated or the API broken currently or the code wrong? @jh-RLI

**Comment by jh-RLI** [comment]
Noting changed should still work. I just tested it locally and on the oep and it work using the table delete button.

**Comment by jh-RLI** [comment]
Maybe you do not have permission? is there any error ?

**Comment by chrwm** [comment]
Sorry for the confusion. 
Apparently you're right. The script works :)

**Comment by jh-RLI** [comment]
No worries. I'm just glad that it works :)
