### ISSUE TITLE
Error while trying to delete tables

### ISSUE THREAD

**Issue by anik-ier** [sedos-project/sedos_upload#5]
**Hi, 

I tried to delete tables with the script. Some tables are deleted, but rest could not be deleted with the following error! 
I noticed that the tables are deleted they were not empty table. Not sure if the info is relevant!** 

2024-05-18 16:10:18,738 - ERROR - 

<!DOCTYPE html>
<html lang="en">
<head>
    

    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title> OEP </title>

    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon"/>

    <link href="/static/fontawesome_5/css/django-fontawesome.css" rel="stylesheet" media="all">
<link href="/static/fontawesome_5/css/all.min.css" rel="stylesheet" media="all">
<script type="text/javascript" src="/static/fontawesome_5/js/django-fontawesome.js"></script>
    <link rel="stylesheet" href="/static/CACHE/css/output.221dd67bb3fd.css" type="text/css">
    
</head>

<body class="d-flex flex-column h-100">

    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img style="width:45px;height: 45px;" src="/static/OpenEnergyFamily_Logo_OpenEnergyPlatform_untitled_white.svg"/>
            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/dataedit/schemas">Database</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownFS" role="button"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Scenario Bundles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownFS">
                            
                            <a class="dropdown-item" href="/scenario-bundles/main">Scenario Bundle</a>
                            <a class="dropdown-item" href="/factsheets/frameworks/">Framework Factsheet</a>
                            <a class="dropdown-item" href="/factsheets/models/">Model Factsheet</a>
                            
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownOntology" role="button"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ontology
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownOntology">
                            <a class="dropdown-item" href="/ontology/">Overview</a>
                            <a class="dropdown-item" href="/ontology/oeo/">OEO Modules</a>
                            <a class="dropdown-item" href="/viewer/oeo/">OEO Viewer</a>
                            <a class="dropdown-item" href="/ontology/oeo-steering-committee/">OEO Steering Committee</a>
                            <a class="dropdown-item" href="https://terminology.tib.eu/ts/collections" target="_blank" data-toggle="tooltip" data-placement="top" title="We want to combine our efforts in ontology development with the TIB as part of the NFDI4Energy project."><i class="fas fa-external-link-alt"></i> TIB Terminology Service</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://openenergyplatform.github.io/academy/" target="_blank">Academy <i class="fas fa-external-link-alt"></i></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAbout" role="button"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownAbout">
                            <a class="dropdown-item" href="/about/">Overview</a>
                            <a class="dropdown-item" href="https://openenergyplatform.github.io/organisation/" target="_blank"><i class="fas fa-external-link-alt"></i> Compendium</a>
                            <a class="dropdown-item" href="https://openenergyplatform.github.io/oeplatform/" target="_blank"><i class="fas fa-external-link-alt"></i> Developer Documentation</a>
                            <a class="dropdown-item" href="https://oeplatform.readthedocs.io/en/latest/?badge=latest" target="_blank"><i class="fas fa-external-link-alt"></i> REST-API Documentation</a>
                            <a class="dropdown-item" href="https://openenergyplatform.github.io/academy/questions/" target="_blank"><i class="fas fa-external-link-alt"></i> FAQ</a>
                        </div>
                    </li>
                </ul>
            </div>
             

                <div class="btn profile-bar">
                    <a class="btn-profile" href="/user/profile/853/settings"><i class="fas fa-user " ></i> 016anik</a>
                    <a class="btn-logout" href="/user/logout/?next=/"><i class="fas fa-arrow-right " ></i> Logout</a>
                </div>

            

        </div>
    </nav>

<main class="main">
    
    
        <div class="content">
            <div class="content__container">
                
                
                    <section class="content__main">
                        

<center>
<h3>This page seems to have an unexpected error!</h3> <br>

It might be due to problems in the data or metadata.<br>
Please use the navigation bar above to continue.<br>

In return, you have the increasingly rare opportunity to marvel at the endangered OEPlatypus:

<a href="/static/img/OpenEnergyFamily_OEPlatypus.png">
    <img style="width:50%" class="mx-auto d-block"
        src="/static/img/OpenEnergyFamily_OEPlatypus.png" alt="OEPlatypus" />
</a>

</center>

                    </section>
                
                
                    <section class="content__side">
                        
                        <div>
                            
                            
                        </div>
                    </section>
                
            </div>
        </div>
    </main>

    <footer class="footer mt-auto py-3 bg-secondary">
        <nav class="navbar navbar-expand navbar-dark bg-secondary">
            <div class="container-fluid justify-content-end">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="/contact/">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/legal/privacy_policy/">Privacy Policy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/legal/tou/">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </nav>
    </footer>

<div id="uiWarnings"></div>

    
    <script src="/static/CACHE/js/output.1ac71a237d60.js"></script>
    

</body>

</html>

Traceback (most recent call last):
  File "C:\Users\ac141435\Desktop\TIMES_2_SEDOS-IAT\upload_script\main.py", line 264, in <module>
    delete_tables(delete_table_folder)
  File "C:\Users\ac141435\Desktop\TIMES_2_SEDOS-IAT\upload_script\main.py", line 242, in delete_tables
    raise logger.error(response.text)
TypeError: exceptions must derive from BaseException

**Comment by anik-ier** [comment]
@chrwm 
@henhuy

**Comment by anik-ier** [comment]
Found one possible reason! It could be that there are tables in the 'delete' folder, which do not exist in the OEP.

**Comment by chrwm** [comment]
> Found one possible reason! It could be that there are tables in the 'delete' folder, which do not exist in the OEP.

Hi @anik-ier this is indeed the case!
The error above occurs when you try to delete a table that is not on the OEP (as it probably existed but was deleted already.)
I'll close the issue. Thanks for bringing it up!
